#!/usr/bin/env bash
# Regenerates the criterion-4 evidence: the import guard and the wrapper test run.
#
#   depguard-run.txt   golangci-lint on the clean tree, then with throwaway imports of CMC and of
#                      the test-only atlstest package planted outside internal/atls (each must
#                      fail and name the import), then clean again after removing them.
#   atls-test-run.txt  go test of internal/atls, plain and under the race detector.
#
# Usage: prove-isolation.sh            (golangci-lint on PATH, or GOLANGCI_LINT=/path/to/it)
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
root=$(git -C "$here" rev-parse --show-toplevel)
lint=${GOLANGCI_LINT:-golangci-lint}
cd "$root"

probe_dir=internal/bddreport
cmc_probe=$probe_dir/zz_cmc_guard_probe.go
atlstest_probe=$probe_dir/zz_atlstest_guard_probe.go
cmc_test_probe=$probe_dir/zz_cmc_guard_probe_test.go
cleanup() { rm -f "$cmc_probe" "$atlstest_probe" "$cmc_test_probe"; }
trap cleanup EXIT

run_lint() {
	local status=0
	"$lint" run "$@" || status=$?
	echo "exit status: $status"
}

{
	echo "# Import guard (depguard) — generated by prove-isolation.sh"
	echo
	echo "$("$lint" --version)"
	echo "$(go version)"
	echo "tree: $(git rev-parse HEAD)$(git diff --quiet HEAD -- . ':!docs/evidences' || echo ' + uncommitted changes')"
	echo

	echo "## 1. Clean tree: no package outside internal/atls imports CMC"
	echo '$ golangci-lint run ./...'
	run_lint ./...
	echo

	echo "## 2. Throwaway import of CMC from a non-test file of $probe_dir"
	cat >"$cmc_probe" <<'EOF'
package bddreport

import _ "github.com/Fraunhofer-AISEC/cmc/attestedtls"
EOF
	echo "\$ cat $cmc_probe"
	cat "$cmc_probe"
	echo "\$ golangci-lint run ./$probe_dir/..."
	run_lint "./$probe_dir/..."
	rm -f "$cmc_probe"
	echo

	echo "## 3. Throwaway import of CMC from a test file of $probe_dir"
	cat >"$cmc_test_probe" <<'EOF'
package bddreport

import _ "github.com/Fraunhofer-AISEC/cmc/attestationreport"
EOF
	echo "\$ cat $cmc_test_probe"
	cat "$cmc_test_probe"
	echo "\$ golangci-lint run ./$probe_dir/..."
	run_lint "./$probe_dir/..."
	rm -f "$cmc_test_probe"
	echo

	echo "## 4. Throwaway import of the test-only atlstest package from a non-test file"
	cat >"$atlstest_probe" <<'EOF'
package bddreport

import _ "github.com/eclipse-xfsc/facis-zero-trust-demonstrator/internal/atls/atlstest"
EOF
	echo "\$ cat $atlstest_probe"
	cat "$atlstest_probe"
	echo "\$ golangci-lint run ./$probe_dir/..."
	run_lint "./$probe_dir/..."
	rm -f "$atlstest_probe"
	echo

	echo "## 5. Throwaway imports removed: clean again"
	echo '$ golangci-lint run ./...'
	run_lint ./...
} >"$here/depguard-run.txt" 2>&1

{
	echo "# internal/atls tests — generated by prove-isolation.sh"
	echo
	echo "$(go version)"
	echo "tree: $(git rev-parse HEAD)$(git diff --quiet HEAD -- . ':!docs/evidences' || echo ' + uncommitted changes')"
	echo
	echo '$ go test -count=1 -v ./internal/atls/...'
	status=0
	go test -count=1 -v ./internal/atls/... 2>&1 | grep -E '^(=== RUN|--- |PASS|FAIL|ok|    )' || status=$?
	echo
	echo '$ go test -race -count=1 ./internal/atls/...'
	go test -race -count=1 ./internal/atls/... 2>&1 || status=$?
} >"$here/atls-test-run.txt"

echo "wrote $here/depguard-run.txt and $here/atls-test-run.txt"
